import { Raleway, Bebas_Neue, Poppins } from "next/font/google";
import "./globals.css";

const rale = Raleway({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
const beba = Bebas_Neue({ subsets: ["latin"], weight: ["400"] });
const pop = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        {/* <link rel="icon" href="/favicon.ico" /> */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="use-credentials"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Poppins:wght@400;700&family=Raleway:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
        <meta viewport="width=device-width, initial-scale=1" />
      </head>
      <body
        className={`${rale.className} ${beba.className} ${pop.className} fcc`}
      >
        {children}
      </body>
    </html>
  );
}
